name: Release Go Binaries

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v24.04.0

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.7"

      - name: Build binary
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist

          EXT=""
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            EXT=".exe"
          fi

          BIN_NAME="szczecin-${{ matrix.goos }}-${{ matrix.goarch }}$EXT"
          echo "Building $BIN_NAME..."

          env CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -ldflags="-s -w" -o "dist/$BIN_NAME" .

          echo "Build completed: dist/$BIN_NAME"

      - name: Upload binaries to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
