- name: Build binary
  run: |
    mkdir -p dist
    EXT=""
    if [ "${{ matrix.goos }}" = "windows" ]; then
      EXT=".exe"
    fi
    BIN_NAME="szczecin-${{ matrix.goos }}-${{ matrix.goarch }}$EXT"
    CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o dist/$BIN_NAME .
