name: Release Go Binaries

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v24.04.0

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.7"

      - name: Build and package binary
        shell: bash
        run: |
          set -euo pipefail

          EXT=""
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            EXT=".exe"
          fi

          BIN_NAME="szczecin$EXT"
          BIN_DIR="build/${{ matrix.goos }}/amd64"
          ARCHIVE_DIR="dist/${{ matrix.goos }}/amd64"

          mkdir -p "$BIN_DIR" "$ARCHIVE_DIR"

          echo "Building $BIN_NAME for ${{ matrix.goos }}/amd64..."
          env CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -ldflags="-s -w" -o "$BIN_DIR/$BIN_NAME" .

          echo "Packaging $BIN_NAME..."

          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            zip -j "$ARCHIVE_DIR/szczecin.zip" "$BIN_DIR/$BIN_NAME"
          else
            tar -czf "$ARCHIVE_DIR/szczecin.tar.gz" -C "$BIN_DIR" "$BIN_NAME"
          fi

      - name: Upload archives to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/szczecin.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
